changelog:
  categories:
    - title: ❌ Breaking changes
      labels:
        - breaking
    - title: 🏕 New features and other improvements
      labels:
        - enhancement
    - title: 🐞 Fixed bugs
      labels:
        - bug
    - title: 👒 Updated dependencies
      labels:
        - dependencies
    - title: 📄 Improved documentation
      labels:
        - documentation
