name: Docker Lint

on:
  pull_request:
    paths:
      - ./Dockerfile
  push:
    branches:
      - main
    tags:
      - 'v*'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  hadolint:
    name: Run hadolint scanning
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run hadolint
        uses: hadolint/hadolint-action@06be81baf89a55ffd0e24b8f04a4185738dd3387 # v3.5.0
        with:
          dockerfile: ./Dockerfile
          format: sarif
          output-file: hadolint-results.sarif
          no-fail: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@ff2f1c621b7f889edc0d3c761ac2e6a3f8cdb0dd # v4.37.7
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true
